// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSrMv8UQMVwKsgGBz6P35K-Qnxt7zSrls',
    appId: '1:499360257834:web:b74eb112c0c6006b3e7053',
    messagingSenderId: '499360257834',
    projectId: 'instaclone-test-1n0b1',
    authDomain: 'instaclone-test-1n0b1.firebaseapp.com',
    storageBucket: 'instaclone-test-1n0b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ9i7AMHLFWRpZqSq6gjin4zl17Xh_RAg',
    appId: '1:499360257834:android:6dbb6b3a67b199553e7053',
    messagingSenderId: '499360257834',
    projectId: 'instaclone-test-1n0b1',
    storageBucket: 'instaclone-test-1n0b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbzwg9GBXqE_oRpbVpmHqgalCqUKCVxlw',
    appId: '1:499360257834:ios:5c66dbda9886f9fc3e7053',
    messagingSenderId: '499360257834',
    projectId: 'instaclone-test-1n0b1',
    storageBucket: 'instaclone-test-1n0b1.appspot.com',
    iosBundleId: 'nam.bui.testProjectInstaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbzwg9GBXqE_oRpbVpmHqgalCqUKCVxlw',
    appId: '1:499360257834:ios:8117c0f355429d273e7053',
    messagingSenderId: '499360257834',
    projectId: 'instaclone-test-1n0b1',
    storageBucket: 'instaclone-test-1n0b1.appspot.com',
    iosBundleId: 'nam.bui.testProjectInstaClone.RunnerTests',
  );
}
